### PR TITLE
86 create api function go get assessment content

### PR DESCRIPTION
**Pull request by ghost**
Completed the works within the scope of the ticket but requires additional work to get information to display in the browser.

### CODE REVIEW

**Review by chrislaupama — CHANGES_REQUESTED** [review]
You will need to remove everything apart from the client consuming the API.

This is WAY too much scope...

You can utilise the additional work you've done with the other tickets to close them off.

Remember to keep in scope and keep things super simple.

**Comment by ghost** [comment]
removed parts required and re-pulled dev branch to bring branch 86 up to date. Should be ready for re-review

**Comment by ghost** [comment]
repulled again. found our duplicated reducers folder and removed and accepted yarn lock changes

**Review by chrislaupama — CHANGES_REQUESTED** [review]
You will need to pull in the latest version of dev to get this PR up to date

**Review by chrislaupama — APPROVED** [review]

**Pull request merged**
